services:
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    command: ["bash", "-c", "./prestart.sh && fastapi run --port 80"]
    image: api
    env_file: apps/api/.env
    volumes:
      - ./apps/api:/app
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: daily_doer
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
